// Generated by CoffeeScript 1.5.0
(function() {

  define(['aloha', 'aloha/plugin', 'jquery', 'ui/ui', 'ui/button'], function(Aloha, Plugin, jQuery, UI, Button) {
    var buffer;
    buffer = '';
    return Plugin.create('copy', {
      getBuffer: function() {
        if (localStorage) {
          return localStorage.alohaOerCopyBuffer;
        } else {
          return buffer;
        }
      },
      buffer: function(content) {
        buffer = content;
        buffer = buffer.replace(/id="[^"]+"/, '');
        if (localStorage) {
          localStorage.alohaOerCopyBuffer = buffer;
        }
        return jQuery('.action.paste').fadeIn('fast');
      },
      init: function() {
        var plugin;
        plugin = this;
        if (localStorage && localStorage.alohaOerCopyBuffer) {
          jQuery('.action.paste').fadeIn('fast');
        }
        return UI.adopt("paste", Button, {
          click: function(e) {
            var range;
            e.preventDefault();
            range = Aloha.Selection.getRangeObject();
            return GENTICS.Utils.Dom.insertIntoDOM(jQuery(plugin.getBuffer()), range, Aloha.activeEditable.obj);
          }
        });
      }
    });
  });

}).call(this);
