// Generated by CoffeeScript 1.3.3
(function() {

  define(['aloha', 'aloha/plugin', 'jquery', 'popover', 'ui/ui', 'css!../../../contrib/angular/css/angular.css'], function(Aloha, Plugin, jQuery, Popover, UI) {
    var EXPRESSION_DIALOG_HTML, VARIABLE_DIALOG_HTML, attachExpressionEvents, attachVariableEvents, expressionPopulator, insertNgVariable, showExpressionDialog, showVariableDialog, startAngular, updateExpression, variablePopulator,
      _this = this;
    VARIABLE_DIALOG_HTML = '<form class="modal" id="angular-variable-modal" tabindex="-1" role="dialog" aria-labelledby="angular-variable-modalLabel" aria-hidden="true">\n  <div class="modal-header">\n    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>\n    <h3 id="angular-variable-modalLabel">Add Variable</h3>\n  </div>\n  <div class="modal-body">\n    <div id="link-text">\n      <h4>Variable name</h4>\n      <div>\n        <input id="angular-variable-name" class="input-xlarge" type="text" placeholder="Enter a variable name here" required />\n      </div>\n    </div>\n  <div class="modal-footer">\n    <button class="btn btn-primary link-save">Submit</button>\n    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>\n  </div>\n</form>';
    EXPRESSION_DIALOG_HTML = '<form class="modal" id="angular-expression-modal" tabindex="-1" role="dialog" aria-labelledby="angular-expression-modalLabel" aria-hidden="true">\n  <div class="modal-header">\n    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>\n    <h3 id="angular-expression-modalLabel">Add Variable</h3>\n  </div>\n  <div class="modal-body">\n    <div id="link-text">\n      <h4>Expression</h4>\n      <div>\n        <input id="angular-expression-name" class="input-xlarge" type="text" placeholder="Enter an expression here" required />\n      </div>\n    </div>\n  <div class="modal-footer">\n    <button class="btn btn-primary link-save">Submit</button>\n    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>\n  </div>\n</form>';
    attachVariableEvents = function($el) {
      $el.alohaBlock();
      return $el.each(function(i, node) {
        var $input, $node;
        $node = jQuery(node);
        $input = $node.children('[ng-model]');
        $node.attr('data-ng-model', $input.attr('ng-model'));
        $node.attr('data-ng-value', $input.val());
        return $input.on('input', function() {
          var val;
          val = parseFloat($input.val());
          return $node.attr('data-ng-value', val);
        });
      });
    };
    attachExpressionEvents = function($el) {
      $el.alohaBlock();
      return $el.each(function(i, node) {
        var $node;
        return $node = jQuery(node);
      });
    };
    startAngular = function($editable) {
      var $allVariables,
        _this = this;
      $editable = $editable.last();
      $allVariables = $editable.find('.ng-model-wrapper');
      angular.bootstrap($editable);
      return $allVariables.each(function(i, el) {
        var $el, $input;
        $el = jQuery(el);
        $input = $el.find('input');
        $input.val($el.attr('data-ng-value') || '0');
        return $input.trigger('input');
      });
    };
    updateExpression = function($el, expression) {
      var $rendered;
      $el.data('ng-expression', expression);
      $rendered = $el.find('.ng-expression-rendered').clone(true);
      $el.find('.ng-expression-rendered').remove();
      $rendered.attr('ng-bind', expression).appendTo($el);
      return startAngular($el.parents('.aloha-editable'));
    };
    Aloha.bind('aloha-editable-activated', function(evt, ed) {
      var $app;
      $app = ed.editable.obj;
      $app.find('[ng-model]').each(function(i, el) {
        var $el, $wrapper;
        $el = jQuery(el);
        if ($el.parent().hasClass('ng-model-wrapper')) {
          return;
        }
        $wrapper = jQuery('<span></span>').addClass('ng-model-wrapper');
        $el.replaceWith($wrapper);
        $wrapper.append($el);
        return attachVariableEvents($wrapper);
      });
      $app.find('[ng-bind]').each(function(i, el) {
        var $el, $wrapper;
        $el = jQuery(el);
        if ($el.parent().hasClass('ng-expression-wrapper')) {
          return;
        }
        $wrapper = jQuery('<span></span>').addClass('ng-expression-wrapper');
        $el.replaceWith($wrapper);
        $wrapper.append($el);
        $wrapper.data('ng-expression', $el.attr('ng-bind'));
        return attachExpressionEvents($wrapper);
      });
      attachExpressionEvents($app.find('.ng-expression-wrapper'));
      return startAngular($app);
    });
    showVariableDialog = function($el, variableText) {
      var $input, dialog, root, variableName, variableValue,
        _this = this;
      root = Aloha.activeEditable.obj;
      dialog = jQuery(VARIABLE_DIALOG_HTML);
      variableValue = parseFloat(variableText);
      variableName = '';
      if (isNaN(variableValue) && /[a-zA-Z]+/.test(variableText)) {
        variableName = variableText;
      }
      if (isNaN(variableValue)) {
        variableValue = 0;
      }
      $el.attr('data-ng-value', variableValue);
      $input = dialog.find('#angular-variable-name');
      $input.val(variableName);
      dialog.on('submit', function(evt) {
        evt.preventDefault();
        variableName = $input.val();
        $el.attr('data-variable', variableName);
        $el.children('input').attr('ng-model', variableName);
        return dialog.modal('hide');
      });
      dialog.modal('show');
      dialog.on('hidden', function() {
        return dialog.remove();
      });
      setTimeout((function() {
        return $input.focus();
      }), 100);
      return dialog;
    };
    showExpressionDialog = function($el, expressionText) {
      var $input, dialog, root,
        _this = this;
      root = Aloha.activeEditable.obj;
      dialog = jQuery(EXPRESSION_DIALOG_HTML);
      $input = dialog.find('#angular-expression-name');
      $input.val(expressionText);
      dialog.on('submit', function(evt) {
        var expression;
        evt.preventDefault();
        expression = $input.val();
        $el.attr('data-expression', expression);
        $el.children().attr('ng-bind', expression);
        return dialog.modal('hide');
      });
      dialog.modal('show');
      dialog.on('hidden', function() {
        return dialog.remove();
      });
      setTimeout((function() {
        return $input.focus();
      }), 100);
      return dialog;
    };
    insertNgVariable = function() {
      var $el, $input, $tail, range, variable;
      $el = jQuery('<span class="ng-model-wrapper aloha-ephemera-wrapper"><input type="number"/></span>');
      range = Aloha.Selection.getRangeObject();
      if (range.isCollapsed()) {
        GENTICS.Utils.Dom.insertIntoDOM($el, range, Aloha.activeEditable.obj);
        $el.trigger('show');
        return makeCloseIcon($el);
      } else {
        $tail = jQuery('<span class="aloha-ephemera-wrapper">&#160;</span>');
        variable = range.getText();
        $el.attr('data-variable', variable);
        $input = $el.children('input');
        $el.append($input);
        $el.attr('ng-model', variable);
        GENTICS.Utils.Dom.removeRange(range);
        return GENTICS.Utils.Dom.insertIntoDOM($el.add($tail), range, Aloha.activeEditable.obj);
      }
    };
    UI.adopt('insertNgVariable', null, {
      click: function() {
        var dialog, newVariable, range, variableText,
          _this = this;
        newVariable = jQuery('<span class="ng-model-wrapper aloha-new-link"><input class="ng-model-input" type="number"/></span>');
        range = Aloha.Selection.getRangeObject();
        variableText = range.isCollapsed() ? "" : range.getText();
        dialog = showVariableDialog(newVariable, variableText);
        return dialog.on('hidden', function() {
          if (!newVariable.data('variable')) {
            return;
          }
          range = Aloha.Selection.getRangeObject();
          if (range.isCollapsed()) {
            GENTICS.Utils.Dom.extendToWord(range);
          }
          if (range.isCollapsed()) {
            GENTICS.Utils.Dom.insertIntoDOM(newVariable, range, Aloha.activeEditable.obj);
            range.startContainer = range.endContainer = newVariable.contents()[0];
            range.startOffset = 0;
            range.endOffset = newVariable.text().length;
          } else {
            GENTICS.Utils.Dom.addMarkup(range, newVariable, false);
          }
          newVariable = Aloha.activeEditable.obj.find('.aloha-new-link');
          newVariable.removeClass('aloha-new-link');
          attachVariableEvents(newVariable);
          return startAngular(Aloha.activeEditable.obj);
        });
      }
    });
    UI.adopt('insertNgExpression', null, {
      click: function() {
        var $newExpression, $rendered, dialog, expressionText, range,
          _this = this;
        range = Aloha.Selection.getRangeObject();
        if (range.startContainer === range.endContainer && range.startOffset === 0 && range.endOffset === range.startContainer.length) {
          $rendered = jQuery(range.getCommonAncestorContainer());
          $newExpression = $rendered.parent();
        } else {
          $newExpression = jQuery('<span class="aloha-new-link ng-expression-wrapper"><span class="ng-expression-rendered"></span></span>');
        }
        expressionText = range.isCollapsed() ? "" : range.getText();
        dialog = showExpressionDialog($newExpression, expressionText);
        return dialog.on('hidden', function() {
          if ($newExpression.children('[ng-bind]')[0]) {
            if (!$newExpression.parent()[0]) {
              if (range.isCollapsed()) {
                GENTICS.Utils.Dom.extendToWord(range);
              }
              $newExpression.addClass('aloha-new-element');
              if (range.isCollapsed()) {
                GENTICS.Utils.Dom.insertIntoDOM($newExpression, range, Aloha.activeEditable.obj);
                range.startContainer = range.endContainer = $newExpression.contents()[0];
                range.startOffset = 0;
                range.endOffset = $newExpression.text().length;
              } else {
                GENTICS.Utils.Dom.addMarkup(range, $newExpression, false);
              }
              $newExpression = Aloha.activeEditable.obj.find('.aloha-new-element');
              $newExpression.removeClass('aloha-new-element');
              $newExpression.alohaBlock();
            }
            return startAngular(Aloha.activeEditable.obj);
          }
        });
      }
    });
    variablePopulator = function($el) {
      var $bubble, $input, $max, $min, $slider, max, min, val;
      $min = jQuery('<input style="width: 2em;"/>');
      $max = jQuery('<input style="width: 2em;"/>');
      $slider = jQuery('<span></span>');
      $bubble = jQuery('<span class="aloha-dialog"></span>');
      $bubble.append($min);
      $bubble.append($slider);
      $bubble.append($max);
      $input = $el.children('[ng-model]');
      min = $input.data('ng-min') || 0;
      max = $input.data('ng-max') || 100;
      val = Math.max(min, Math.min($el.attr('data-ng-value') || 0, max));
      $min.val(min);
      $max.val(max);
      $slider.slider({
        min: min,
        max: max,
        value: val,
        slide: function(event, ui) {
          val = ui.value;
          $input.val(val);
          $input.trigger('input');
          return $el.attr('data-ng-value', val);
        }
      });
      $min.on('input', function() {
        val = $min.val();
        $el.data('ng-min', val);
        return $slider.slider({
          min: val
        });
      });
      $max.on('input', function() {
        val = $max.val();
        $el.data('ng-max', val);
        return $slider.slider({
          max: val
        });
      });
      return $bubble;
    };
    expressionPopulator = function($el) {
      var $bubble, $done, $expression;
      $expression = jQuery('<input style="width: 7em;"/>');
      $done = jQuery('<button class="btn btn-primary">Done</button>');
      $bubble = jQuery('<span class="aloha-dialog"></span>');
      $bubble.append($expression);
      $bubble.append($done);
      $expression.val($el.children('[ng-bind]').attr('ng-bind'));
      $done.on('click', function() {
        var expression;
        expression = $expression.val();
        updateExpression($el, expression);
        return $el.popover('hide');
      });
      return $bubble;
    };
    Popover.register({
      hover: false,
      selector: '.ng-model-wrapper',
      populator: variablePopulator
    });
    return Popover.register({
      hover: false,
      selector: '.ng-expression-wrapper',
      populator: expressionPopulator
    });
  });

}).call(this);
