// Generated by CoffeeScript 1.5.0

/*
Register a couple of assorted oer plugins
*/


(function() {

  define(['aloha/plugin', 'jquery', 'overlay/overlay-plugin', './link', './image'], function(Plugin, $, Popover, linkConfig, imageConfig) {
    return Plugin.create('assorted', {
      defaultSettings: {
        image: {
          preview: true
        }
      },
      init: function() {
        this.settings = $.extend(true, this.defaultSettings, this.settings);
        Popover.register(linkConfig);
        return Popover.register(imageConfig);
      }
    });
  });

}).call(this);
