// Generated by CoffeeScript 1.3.3

/*
Register a couple of assorted oer plugins
*/


(function() {

  define(['popover', './link', './image', './figure', './title-figcaption', './simulation'], function(Popover, linkConfig, imageConfig, figureConfig, figcaptionConfig, simulationConfig) {
    Popover.register(linkConfig);
    Popover.register(imageConfig);
    Popover.register(figcaptionConfig);
    return Popover.register(simulationConfig);
  });

}).call(this);
