// Generated by CoffeeScript 1.5.0
(function() {

  define(['aloha', 'aloha/plugin', 'jquery', 'aloha/ephemera', 'ui/ui', 'ui/button', 'semanticblock/semanticblock-plugin', 'css!equation/css/equation-plugin.css'], function(Aloha, Plugin, jQuery, Ephemera, UI, Button, semanticBlock) {
    var TEMPLATE;
    TEMPLATE = '<div class="equation"></div>';
    return Plugin.create('equation', {
      getLabel: function() {
        return 'Equation';
      },
      selector: '.equation',
      activate: function($element) {
        var $body, $contents;
        $contents = $element.contents();
        if ($contents.text().trim().length === 0) {
          $contents = '';
        }
        $body = jQuery('<p></p>').attr('placeholder', 'Enter your math notation here');
        $element.empty().append($body.append($contents));
        return $element.click(function() {
          $body.removeClass('aloha-empty');
          if ($body.html().trim().length === 0) {
            console.log('asdf');
            return Aloha.require(['math/math-plugin'], function(MathPlugin) {
              console.log('qwer');
              return MathPlugin.insertMathInto($body);
            });
          }
        });
      },
      deactivate: function($element) {
        var $contents;
        $contents = $element.find('math');
        return $element.html($contents);
      },
      init: function() {
        semanticBlock.register(this);
        UI.adopt("insert-equation", Button, {
          click: function(e) {
            e.preventDefault();
            return semanticBlock.insertAtCursor(jQuery(TEMPLATE));
          }
        });
        return UI.adopt("insertEquation", Button, {
          click: function(e) {
            e.preventDefault();
            return semanticBlock.insertAtCursor(jQuery(TEMPLATE));
          }
        });
      }
    });
  });

}).call(this);
