// Generated by CoffeeScript 1.5.0
(function() {

  define(['aloha', 'aloha/plugin', 'jquery', 'aloha/ephemera', 'ui/ui', 'ui/button', 'semanticblock/semanticblock-plugin', 'css!quotation/css/quotation-plugin.css'], function(Aloha, Plugin, jQuery, Ephemera, UI, Button, semanticBlock) {
    var TEMPLATE;
    TEMPLATE = "<div class=\"quotation\"></div>";
    return Plugin.create('quotation', {
      init: function() {
        var _this = this;
        semanticBlock.activateHandler('.quotation', function($element) {
          return $element.aloha();
        });
        semanticBlock.deactivateHandler('.quotation', function($element) {
          $element.mahalo();
          return $element.attr('class', 'quotation');
        });
        UI.adopt("insert-quotation", Button, {
          click: function() {
            return semanticBlock.insertAtCursor(jQuery(TEMPLATE));
          }
        });
        return UI.adopt("insertQutoation", Button, {
          click: function() {
            return semanticBlock.insertAtCursor(jQuery(TEMPLATE));
          }
        });
      }
    });
  });

}).call(this);
