// Generated by CoffeeScript 1.5.0
(function() {

  define(['aloha', 'aloha/plugin', 'jquery', 'aloha/ephemera', 'ui/ui', 'ui/button', 'semanticblock/semanticblock-plugin', 'css!note/css/note-plugin.css'], function(Aloha, Plugin, jQuery, Ephemera, UI, Button, semanticBlock) {
    var TEMPLATE;
    TEMPLATE = '<div class="note">\n    <div class="title-container dropdown">\n        <a class="type" data-toggle="dropdown">Note</a>\n        <ul class="dropdown-menu">\n            <li><a href="">Note</a></li>\n            <li><a href="">Aside</a></li>\n            <li><a href="">Warning</a></li>\n            <li><a href="">Tip</a></li>\n            <li><a href="">Important</a></li>\n        </ul>\n        <span class="title" semantic-editable placeholder="Add a title (optional)"></span>\n    </div>\n    <div class="body" semantic-editable placeholder="Type the text of your note here."></div>\n</div>';
    return Plugin.create('note', {
      init: function() {
        semanticBlock.enableDragToAdd('Note to Reader', '[semantic-drag-source=note]', TEMPLATE);
        return UI.adopt('insertNote', Button, {
          click: function(a, b, c) {
            return semanticBlock.insertAtCursor(TEMPLATE);
          }
        });
      }
    });
  });

}).call(this);
